name: podcast-dl-gael
version: "v3.5-20260124"
base: core24
summary: A simple script to download podcasts from YouTube or RSS feeds
description: |
  A simple script to download videos/podcasts from YouTube or RSS feeds.
  Behind the scene it uses [yt-dlp](https://github.com/yt-dlp/yt-dlp), deno and Python's feedparser.
  By default, new files are downloaded everyday at 06:00.

grade: stable
confinement: strict

platforms:
  arm64:
  armhf:
  amd64:

license: "GPL-3.0"

apps:
  podcast-dl:
    command: podcast-dl/podcast-dl.sh
    environment:
      PATH: $PATH:$SNAP_COMMON/podcast-dl/bin
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
    daemon: simple
    timer: 06:00
    plugs:
      - network
      - home

  download-now:
    command: podcast-dl/podcast-dl.sh
    environment:
      PATH: $PATH:$SNAP_COMMON/podcast-dl/bin
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
    plugs:
      - network
      - home

  rss-skip-download:
    command: podcast-dl/rss-skip-download.sh
    environment:
      PATH: $PATH:$SNAP_COMMON/podcast-dl/bin
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

  youtube-dl-skip-download:
    command: podcast-dl/youtube-dl-skip-download.sh
    environment:
      PATH: $PATH:$SNAP_COMMON/podcast-dl/bin
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

parts:
  podcast-dl:
    plugin: dump
    source: snap/local/
    stage-packages:
      - curl
      - python3-requests
      - python3-feedparser

  deno:
    plugin: nil
    override-build: |

      # Detect architecture and set download URL
      case "$CRAFT_ARCH_BUILD_FOR" in
        amd64)
          DENO_URL="https://github.com/denoland/deno/releases/download/v2.6.6/deno-x86_64-unknown-linux-gnu.zip"
          ;;
        arm64)
          DENO_URL="https://github.com/denoland/deno/releases/download/v2.6.6/deno-aarch64-unknown-linux-gnu.zip"
          ;;
        *)
          echo "Unsupported architecture for deno: $CRAFT_ARCH_BUILD_FOR"
          ;;
      esac

      # Download and extract Deno
      if [ ! -z ${DENO_URL+x} ]; then
          
          wget "$DENO_URL" -O deno.zip
          unzip deno.zip

          chmod +x deno

          mkdir -p $CRAFT_PART_INSTALL/podcast-dl/bin
          mv deno $CRAFT_PART_INSTALL/podcast-dl/bin/
      fi

      craftctl default

    stage-packages:
      - wget
      - unzip

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libglu1-mesa
      - freeglut3-dev
      - libpulse0
