name: podcast-dl-gael
version: "2.0-20230802"
base: core20
summary: A simple script to download podcasts from YouTube or RSS feeds
description: |
  A simple script to download videos/podcasts from YouTube or RSS feeds.
  Behind the scene it uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) and Python's feedparser.
  New files are downloaded everyday at 06:00.

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

license: "GPL-3.0"

apps:
  podcast-dl:
    command: podcast-dl/podcast-dl.sh
    environment:
      PYTHONPATH: $SNAP/lib/python3.8/site-packages
      LD_LIBRARY_PATH: $SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    daemon: simple
    timer: 06:00
    plugs:
      - network

parts:
  podcast-dl:
    plugin: dump
    source: snap/local/

  python-env:
    plugin: python
    python-packages:
      - requests
      - feedparser

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libglu1-mesa
      - freeglut3
      - libpulse0

  utils:
    plugin: nil
    stage-packages:
      - curl
