name: podcast-dl-gael
version: "1.0-20210827"
base: core20
summary: A simple script I use to download podcasts from YouTube and RSS feeds
description: A simple script I use to download podcasts from YouTube and RSS feeds. It uses youtube-dl (https://youtube-dl.org/) and a (badly written) bash script. Files are then synchronized to my laptop and mobile using syncthing (https://snapcraft.io/syncthing-gael).

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

license: "GPL-3.0"

apps:
  podcast-dl:
    command: podcast-dl/podcast-dl.sh
    daemon: simple
    timer: 06:00
    plugs:
      - network

parts:
  podcast-dl:
    plugin: dump
    source: snap/local/

  youtube-dl-env:
    plugin: python
    python-packages: []
    stage-packages:
      - curl
