name: podcast-dl-gael
version: "v3.4-20250708"
base: core24
summary: A simple script to download podcasts from YouTube or RSS feeds
description: |
  A simple script to download videos/podcasts from YouTube or RSS feeds.
  Behind the scene it uses [yt-dlp](https://github.com/yt-dlp/yt-dlp) and Python's feedparser.
  By default, new files are downloaded everyday at 06:00.

grade: stable
confinement: strict

platforms:
  arm64:
  armhf:
  amd64:

license: "GPL-3.0"

apps:
  podcast-dl:
    command: podcast-dl/podcast-dl.sh
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
    daemon: simple
    timer: 06:00
    plugs:
      - network
      - home

  download-now:
    command: podcast-dl/podcast-dl.sh
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack
    plugs:
      - network
      - home

  rss-skip-download:
    command: podcast-dl/rss-skip-download.sh
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

  youtube-dl-skip-download:
    command: podcast-dl/youtube-dl-skip-download.sh
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    plugs:
      - network

parts:
  podcast-dl:
    plugin: dump
    source: snap/local/
    stage-packages:
      - curl
      - python3-requests
      - python3-feedparser

  ffmpeg:
    plugin: nil
    stage-packages:
      - ffmpeg
      - libglu1-mesa
      - freeglut3-dev
      - libpulse0
